srcdir = .

prefix ?= /usr
bindir ?= /usr/bin
sbindir ?= /usr/sbin
libexecdir ?= /usr/libexec
datarootdir ?= /usr/share
datadir ?= /usr/share
sysconfdir ?= /usr/etc
libdir ?= /usr/lib
mandir ?= /usr/share/man
